### ISSUE TITLE
pip-compile 1.4.4 fails with pip 8.0.0

### ISSUE THREAD

**Issue by rleonhardt** [nvie/pip-tools#304]
pip-tools==1.4.4
pip==8.0.0
setuptools==19.4
Python 3.4.4
Mac OS X 10.11.3

```
$ pip-compile requirements/base.in
Traceback (most recent call last):
  File "/python3.4/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/python3.4/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/python3.4/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/python3.4/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/python3.4/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/python3.4/lib/python3.4/site-packages/piptools/scripts/compile.py", line 141, in cli
    results = resolver.resolve()
  File "/python3.4/lib/python3.4/site-packages/piptools/resolver.py", line 78, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/python3.4/lib/python3.4/site-packages/piptools/resolver.py", line 154, in _resolve_one_round
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/python3.4/lib/python3.4/site-packages/piptools/resolver.py", line 154, in <genexpr>
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/python3.4/lib/python3.4/site-packages/piptools/resolver.py", line 201, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/python3.4/lib/python3.4/site-packages/piptools/repositories/pypi.py", line 94, in find_best_match
    all_candidates = self.find_all_versions(ireq.name)
  File "/python3.4/lib/python3.4/site-packages/piptools/repositories/pypi.py", line 83, in find_all_versions
    self._available_versions_cache[req_name] = self.finder._find_all_versions(req_name)
AttributeError: 'PackageFinder' object has no attribute '_find_all_versions'
```
When I downgrade to pip==1.7.2, everything works normally.

**Comment by nvie** [comment]
"Fixed" in 1.4.5. For now, you'll have to use pip 7. I'll look into what the upgrade to 8.0 meant for the internals, and try to fix things so pip-tools works with 8.0+ later.

**Comment by rleonhardt** [comment]
Thanks for the "fix", it's working ;-)
```pip-compile currently does not work with pip version 8.0+ yet (8.0.0 found),```

Maybe you want to remove the last 2 characters of the format string? `, `

I hope you can adapt to the new pip internals soon.

**Comment by yetanotherportfolio** [comment]
new version of pip just came out (8.0.1) that fix that message

**Comment by nvie** [comment]
I've just released pip-tools==1.5, adding support for pip>=8. Have fun :)

**Comment by nim65s** [comment]
Thanks V :D

**Comment by benje** [comment]
:+1: thank you
