### ISSUE TITLE
[future] pip-compile: Error: 'Logger' object has no attribute 'addHandler'

### ISSUE THREAD

**Issue by rossgzc** [nvie/pip-tools#144]
When trying to run pip-compile the following error occurs: 

```
Traceback (most recent call last):
  File "/srv/app/env/bin/pip-compile", line 9, in <module>
    load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
  File "/srv/app/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/srv/app/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/srv/app/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/app/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/srv/app/env/src/pip-tools-future/piptools/scripts/compile.py", line 172, in cli
    setup_logging(verbose)
  File "/srv/app/env/src/pip-tools-future/piptools/scripts/compile.py", line 53, in setup_logging
    pip_logger.addHandler(pip_handler)
AttributeError: 'Logger' object has no attribute 'addHandler'
```

Am I missing any dependencies? 

I am running pip-compile on a virtualenv with python 2.7.6

This was working until recently that I had to reinstall my env and the error started appearing. 

If anyone could shed some light my way I would be grateful. I love using pip-compile to manage my requirements.

Thanks!

**Comment by jamezpolley** [comment]
I had this error, and fixed it by upgrading pip. 

My system pip was  pip 1.5.6 and had this error; once I upgraded I got 6.1.1 and the error was gone.

**Comment by rossgzc** [comment]
Thanks for your reply @jamezpolley! That worked :)
